import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import "../i18";

import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Input, Label } from "../Modules/IndexPage/components/components";
import { useKeydown } from "../utils/hooks/useKeydown";
import Spinner from "../components/Spiner";

const Home: NextPage = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loginFailed, setLoginFailed] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const router = useRouter();
  const session = useSession();

  const sessionData = session.data;
  function handleErrorMessage(url: string) {
    if (url.includes("UNAUTHORIZED")) {
      setErrorMessage("Feil brukernavn eller passord");
      return;
    }

    setErrorMessage("Something went wrong, try again");
  }
  const onSubmit = async () => {
    setLoading(true);
    setLoginFailed(false);
    await signIn("credentials", {
      email: username,
      password: password,
      redirect: false,
      callbackUrl: `/${session?.data?.user?.organizationId ?? ""}/dashboard`,
    })
      .then((res) => {
        if (res?.status == 401 || res?.ok == false) {
          handleErrorMessage(res?.error ?? "");
          setLoginFailed(true);
        }
        setLoading(false);
      })
      .catch((err) => {
        setLoginFailed(true);
        setLoading(false);
        console.warn(err);
      });
  };

  useKeydown("Enter", () => {
    void onSubmit();
  });

  useEffect(() => {
    if (session.data?.user.organizationId) {
      router
        .push(`/${session.data.user.organizationId}/dashboard`)
        .catch((err) => console.warn(err));
    } else {
    }

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session]);

  return (
    <>
      <Head>
        <title>L2T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Straffe<span className="text-[hsl(280,100%,70%)]">Pils</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-1 md:gap-8"></div>
          <div className="flex flex-col items-center gap-2">
            <Label>{loginFailed && errorMessage}</Label>
            <Input
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Brukernavn"
            />
            <Input
              type="password"
              placeholder="Passord"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />

            <p className="text-center text-white">
              {session.status == "authenticated" &&
                !session.data.user.organizationId && (
                  <>
                    <p>
                      You were successfully registered but you are not
                      associated with any organization. To sign in with an
                      organization, please contact your administrator for a
                      login link.
                    </p>
                    <p>You will now be logged out.</p>
                  </>
                )}
            </p>
            {loading ? (
              <Spinner />
            ) : (
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={() => {
                  void onSubmit();
                }}
              >
                {sessionData ? "Sign out" : "Sign in"}
              </button>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
