import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import "../i18";

import { api } from "../utils/api";
import { useTranslation } from "react-i18next";
import { useAdmin } from "../utils/admin/useAdmin";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import styled from "styled-components";

const LoginWrapper = styled.div`
  display: flex;
  background-color: white;
  width: 9rem;
  border-radius: 0.3rem;
  height: 3rem;
  justify-content: center;
  align-items: center;
  align-content: center;

  &:hover {
    cursor: pointer;
    background: ${(props) => props.theme.colors.lightGreen};
  }
`;

const Home: NextPage = () => {
  const [wait, setWait] = useState(false);
  const router = useRouter();
  const user = useUser();
  const { mutate, isLoading: meLoading } =
    api.users.addUserToOrganization.useMutation();

  return (
    <>
      <Head>
        <title>L2T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Straffe<span className="text-[hsl(280,100%,70%)]">Pils</span>
          </h1>

          <LoginWrapper>
            {!user.isSignedIn && <SignInButton redirectUrl="/redirect" />}
            {!!user.isSignedIn && <SignOutButton />}
          </LoginWrapper>
        </div>
      </main>
    </>
  );
};

export default Home;
